import "./globals.css";
import Link from "next/link";
import Header from "@/components/Header/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next Aeeepp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  //const [menu, setMenu] = useState([about, portfolio, contact]);
  return (
    <html lang="fr">
      <body className="">
        <Header />
        <div>
          <nav className="p-2 bg-red-300">
            <ul className="flex justify-center gap-2">
              {/* {menu.map((titre) => (
                <li>{titre}</li>
              ))} */}
              <li className="nav-item">
                <Link href="/">home</Link>
              </li>
              <li className="nav-item">
                <Link href="/about">about</Link>
              </li>
              <li className="nav-item">
                <Link href="/contact">contact</Link>
              </li>
              <li className="nav-item">
                <Link href="/create">CreerPost</Link>
              </li>
            </ul>
          </nav>
        </div>
        {children}

        {/*  NOTIFICATIONS */}
        <ToastContainer position="bottom-right" />
      </body>
    </html>
  );
}
